### ISSUE TITLE
No syncing after running black on *ju.py file

### ISSUE THREAD

**Issue by mr-majkel** [SUSTech-data/neopyter#5]
Hi,

after running black reformatter (with `:!black %`) on the python script, the contents of jupyter notebook are not changed, and running `Neopyter sync current` is not doing anything. Turning off kernel, or restarting jupyter lab is also not helping. Is there some kind of cache that needs to be invalidated for the full sync to happen?

Edit: I'm on commit 64e5318

**Comment by AbaoFromCUG** [comment]
Sorry for the delayed replay, I am the developer of this plugin, but some issues with repository settings, I don't receive notification timely.

Neopyter don't cache anything，which sync (buffer)<-->(jupyter lab state in the browser). In other words, neopyter only listen the change of buffer.

`:!black %` format the current file(instead of current buffer) ，so，if your neovim don't read reload file content to buffer, neopyter can't sync anything.
